import type { Student, Certificate, Program } from "@/types/student"

export const PROGRAMS: Program[] = [
  {
    id: "1",
    title: "Computer Science & Engineering",
    slug: "CSE",
    description: "Comprehensive program covering software development, algorithms, data structures, and emerging technologies",
    duration: "4 years",
  },
  {
    id: "2",
    title: "Artificial Intelligence & Machine Learning",
    slug: "AIML",
    description: "AI/ML algorithms, deep learning, neural networks, and intelligent systems",
    duration: "4 years",
  },
  {
    id: "3",
    title: "Data Science",
    slug: "DS",
    description: "Big data analytics, statistical modeling, data mining, and business intelligence",
    duration: "4 years",
  },
  {
    id: "4",
    title: "Internet of Things",
    slug: "IoT",
    description: "Embedded systems, sensor networks, IoT architecture, and smart device programming",
    duration: "4 years",
  },
  {
    id: "5",
    title: "Cyber Security",
    slug: "CSBS",
    description: "Network security, cryptography, ethical hacking, and digital forensics",
    duration: "4 years",
  },
  {
    id: "6",
    title: "AI Research",
    slug: "AIR",
    description: "Advanced AI research, machine learning models, and intelligent system design",
    duration: "4 years",
  },
  {
    id: "7",
    title: "Cloud & Security",
    slug: "CSD",
    description: "Cloud computing, distributed systems, and advanced security protocols",
    duration: "4 years",
  },
  {
    id: "8",
    title: "Electronics & Communication",
    slug: "EC",
    description: "Electronic circuits, communication systems, and embedded technologies",
    duration: "4 years",
  },
  {
    id: "9",
    title: "Electrical Engineering",
    slug: "EE",
    description: "Power systems, electrical machines, and control systems",
    duration: "4 years",
  },
  {
    id: "10",
    title: "Embedded Systems",
    slug: "EX",
    description: "Microcontrollers, real-time systems, and hardware-software integration",
    duration: "4 years",
  },
  {
    id: "11",
    title: "Mechanical Engineering",
    slug: "ME",
    description: "Thermodynamics, manufacturing processes, and mechanical system design",
    duration: "4 years",
  },
  {
    id: "12",
    title: "Civil Engineering",
    slug: "CE",
    description: "Structural engineering, construction management, and infrastructure development",
    duration: "4 years",
  },
]

export const MOCK_STUDENTS: Student[] = [
  {
    university_enrolment_number: "0101CS211001",
    name: "Aditya Verma",
    branch: "CSE",
    college: "GGITS",
    email_id: "aditya.verma@example.com",
    mobile_number: "+91-9876543210",
    upload_your_latest_professional_photo: "/diverse-student-studying.png",
    latest_resume_link: "#",
    student_folder_link: "#",
    github_profile_link: "https://github.com",
    linkedin_profile_link: "https://linkedin.com",
    leetcode_profile_link: "https://leetcode.com",
  },
  {
    university_enrolment_number: "0101CS211002",
    name: "Ishita Sharma",
    branch: "CSE-AIML",
    college: "GGITS",
    email_id: "ishita.sharma@example.com",
    mobile_number: "+91-9876543410",
    upload_your_latest_professional_photo: "/diverse-students-studying.png",
    latest_resume_link: "#",
    student_folder_link: "#",
    github_profile_link: "https://github.com",
    linkedin_profile_link: "https://linkedin.com",
    leetcode_profile_link: "https://leetcode.com",
  },
  {
    university_enrolment_number: "0101CS211003",
    name: "Rahul Kumar",
    branch: "CSE-DS",
    college: "GGCT",
    email_id: "rahul.k@example.com",
    mobile_number: "+91-9988776655",
    upload_your_latest_professional_photo: "/diverse-students-studying.png",
    latest_resume_link: "#",
    student_folder_link: "#",
    github_profile_link: "https://github.com",
    linkedin_profile_link: "https://linkedin.com",
  },
  {
    university_enrolment_number: "0101CS211004",
    name: "Priya Singh",
    branch: "CSE",
    college: "GGITS",
    email_id: "priya.singh@example.com",
    mobile_number: "+91-9123456789",
    upload_your_latest_professional_photo: "/diverse-group-studying.png",
    latest_resume_link: "#",
    student_folder_link: "#",
    github_profile_link: "https://github.com",
    linkedin_profile_link: "https://linkedin.com",
    leetcode_profile_link: "https://leetcode.com",
  },
  {
    university_enrolment_number: "0101CS211005",
    name: "Rohan Das",
    branch: "CSE",
    college: "GGCT",
    email_id: "rohan.das@example.com",
    mobile_number: "+91-9988112233",
    upload_your_latest_professional_photo: "/student5-artwork.png",
    latest_resume_link: "#",
    student_folder_link: "#",
    github_profile_link: "https://github.com",
    linkedin_profile_link: "https://linkedin.com",
  },
]

export const MOCK_CERTIFICATES: Certificate[] = [
  {
    id: "c1",
    name: "AWS Certified Cloud Practitioner",
    mimeType: "application/pdf",
    webViewLink: "#",
    webContentLink: "#",
    thumbnailLink: "/placeholder.svg?height=200&width=300&text=AWS+Certificate",
  },
  {
    id: "c2",
    name: "Introduction to Python - Coursera",
    mimeType: "application/pdf",
    webViewLink: "#",
    webContentLink: "#",
    thumbnailLink: "/placeholder.svg?height=200&width=300&text=Python+Certificate",
  },
  {
    id: "c3",
    name: "Data Structures - Udemy",
    mimeType: "image/jpeg",
    webViewLink: "#",
    webContentLink: "#",
    thumbnailLink: "/placeholder.svg?height=200&width=300&text=DSA+Certificate",
  },
]
